### ISSUE TITLE
버튼 이벤트 구현

### ISSUE THREAD

**Issue by jjPark9** [syoroby/Team_workiing_directory#2]
시작 화면에서 버튼 클릭시 기존에 짜놓은 코드의 기능이 실행될 수 있도록 구현하는 데에 어려움이 있습니다.
좋은 방법이나 코드를 알고계시면 공유 부탁드립니다.

**Comment by Hong-sk** [comment]
안녕하세요! 같은 수업 수강하고 있는 홍성권이라고 합니다. 
tkinter는 잘 모르지만  코드를 읽어보았는데 도움이 될 거 같아서 댓글 달아드려요.

피타고라스 공식을 예를 들면
피타고라스 내에 있는 코드들을 함수로 묶어주어서 해당 모듈을 gittkinterexe.py에서 import하시고 command로 함수를 사용하시면 될 거 같아요!

Pythagoras.py에서 예를 들어 피타고라스 공식을 a라는 함수로 묶어주었다면, 
gittkinterexe.py에서 import Pythagoras를 해주고
버튼 만들어 줄 때, b2=button = Button(window, text = "피타고라스의 함수", command = Pythagoras.a)를 하시면 실행될 거 같습니다!!

**Comment by jjPark9** [comment]
버튼 이벤트 해결하였습니다.
의견 주신 홍성권 학우님 감사합니다.
